package com.sdnx.st.constants.interfaceConstants;

public enum RR001 {
	APPBUSITYPE            ,  //贷款产品
	CUSTID                 ,  //客户编号
	CNAME                  ,  //客户名称
	CARDTYPE               ,  //证件类型
	PERCARDNUM             ,  //证件号码
	CUSTTYPE               ,  //客户类型
	INDUSTRY               ,  //行业分类
	EDUCATIONLEVEL         ,  //最高学历
	AGE                    ,  //年龄
	SEX                    ,  //性别
	MARRIGE                ,  //婚姻状况
	IFHAVECHILD            ,  //有无子女
	MARRIGEDATE            ,  //结婚（离婚）证登记日期
	VOCATIONMIN            ,  //职业细分
	EMPLOYERTIME           ,  //本单位工作起始年份
	SECUREMONEY            ,  //医疗保险上年度合计缴纳金额
	CUSTWORKINFO           ,  //借款人及家庭成员工作状况
	IFBUYHOUSE             ,  //是否在城区购买商住商用房
	APPREQLMT              ,  //申请金额
	FAMANNUINCOME          ,  //截止目前家庭收入
	FAMANNUINOUT           ,  //截止目前家庭支出
	LASTFAMINCOME          ,  //上年度家庭收入
	LASTFAMINOUT           ,  //上年度家庭支出
	FAMINCOMEBEFORE        ,  //前年家庭收入
	FAMINCOMEBEFOUT        ,  //前年家庭支出
	FAMDEBT                ,  //家庭总负债
	FAMASSET               ,  //家庭总资产
	BXNUM                  ,  //有人身意外伤害保险或工伤保险的员工数量
	EMPLOYEENUM            ,  //职工人数（雇员人数）
	IFBUYGARAGE            ,  //是否购买车库
	FIRSTPAYRATE           ,  //首付比例
	JJXMBUILDAREA          ,  //大棚面积
	JJXMLMT                ,  //种植/养殖/经营年限
	JJXMPPE                ,  //经营项目固定资产
	CARNUM                 ,  //营运车辆数量
	FIELDAREAZY            ,  //经营场地面积（含自有）
	FIELDAREAZL            ,  //生产经营场所总建筑面积（含租赁）
	HOUSENUM               ,  //拟购房屋套数
	HOUSETYPE			   ,  //拟购房屋类别
	ZYHOUSENUM			   ,  //自有房产数量
	LASTYSR                ,  //上年度经营收入
	LASTYZC                ,  //上年度经营支出
	DBSUMBALAMT1           ,  //对外担保本金余额（家庭）
	DBSUMBALAMT2           ,  //对外担保本金余额（征信）
	JOINWENTURE            ,  //与下游客户的平均合作年限 
	IFGDRFFGZ              ,  //是否在固定日发放工资 
	LASTTHREEYSR           ,  //近三年经营收入 
	LASTTHREEYZC           ,  //近三年经营支出 
	ACCRECEIVABLE          ,  //经营项目应收账款 
	OPERATEDEBT            ,  //经营项目负债 
	APPDATECYCLE           ,  //申请时点所在周期
	APPDATELOANNUM         ,  //申请时点未结清账户数
	IFEXISTCREDIT          ,  //是否有征信报告
	SIXMOVERDUENUM         ,  //最近6个月本息的逾期次数（征信）
	ONEYOVERDUENUM         ,  //最近12个月本息的逾期次数（征信）
	TOWYOVERDUENUM         ,  //最近24个月本息的逾期次数（征信）
	THREEYOVERDUENUM       ,  //最近36个月本息的逾期次数（征信）
	SIXMOVERDUETERM        ,  //最近6个月本息最大逾期期数（征信）
	TOWYOVERDUETERM        ,  //最近24个月本息最大逾期期数（征信）
	SIXMCHECKNUM           ,  //最近6个月征信报告查询次数
	ONEYCHECKNUM           ,  //最近12个月征信报告查询次数
	TOWYCHECKNUM           ,  //最近24个月征信报告查询次数
	THREEYCHECKNUM         ,  //最近36个月征信报告查询次数
	MINOVERDUETDATE        ,  //最近一次本息逾期距离现在的月数(征信）
	FIRSTACCMONTH          ,  //最早贷款账户距今月数（征信）
	ONEYKHNUM             ,  //最近12个月贷记卡开户个数（征信）
	CCARDNUM                ,  //信用卡数量（不含销户）
	BHMINRATEOVERDUETDATE  ,  //最近一次利息逾期距离现在的月数(本行）
	BHMINOVERDUETDATE      ,  //最近一次本金逾期距离现在的月数(本行）
	BHSIXMOVERDUENUM       ,  //最近6个月本息的逾期次数（本行）
	BHONEYOVERDUENUM       ,  //最近12个月本息的逾期次数（本行）
	BHTOWYOVERDUENUM       ,  //最近24个月本息的逾期次数（本行）
	BHTHREEYOVERDUENUM     ,  //最近36个月本息的逾期次数（本行）
	BHSIXMOVERDUETERM      ,  //最近6个月本息最大逾期期数（本行）
	BHTOWYOVERDUETERM      ,  //最近24个月本息最大逾期期数（本行）
	ONEYSDAILY             ,  //近12个月（存款+理财）日均额
	SIXMSDAILY             ,  //近6个月（存款与理财）日均额
	NINEMDAILY             ,  //近9个月（存款与理财）日均额
	SIXMDAILY              ,  //近6个月日均存款金额
	ONEYDAILY              ,  //近12个月日均存款金额
	ONEYSPOSNUM            ,  //最近12个月ATM与POS交易次数之和（夜间）
	ONEYPOSNUM             ,  //最近12个月POS交易次数（夜间）
	APPOPENNUM             ,  //贷款申请时点敞口数
	APPOTHEROPENNUM        ,  //申请时点前其他敞口个数
	FIRSTLOANDAY           ,  //与银行交易时长
	BHONEYRATEOVERDUETERM  ,  //最近12个月利息最大逾期期数（本行）
	BHLOANBAL			   ,  //我行贷款余额
	THLOANBAL              ,  //他行贷款余额
	DEBITCARDUSEDAMT       ,  //贷记卡已用额度
	ZDEBITCARDUSEDAMT      ,  //准贷记卡透支余额
	USEUAMT                ,  //有效授信额度
	JJXMCL				   ,  //存货数量
	BUSITYPE               ,  //业务品种
	ONEYOVERDUETERM        ,  //最近12个月本息最大逾期期数（征信）
	CREDITCARDFLAG		   ,  //有无行内银行卡
	DEPOSITINFOFLAG        ,  //有无行内存款信息
	CONTROLLERCHANGE	   ,  //近3年实际控制人是否变更
	IFFIXEDWORK            ,  //是否有固定工作
	RRMODEL                ;  //评级模型类型

}
